# Generated by Django 5.0.7 on 2024-11-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
